CREATE TABLE IF NOT EXISTS `multe` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `player_id` INT NOT NULL,
    `player_name` VARCHAR(100) NOT NULL,
    `amount` DECIMAL(10,2) NOT NULL,
    `reason` TEXT NOT NULL,
    `timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `location` VARCHAR(255) NOT NULL
);
