RegisterNUICallback("get-news", function(_, cb)
    lib.callback("b-phone:server:GetNews", false, function(news)
        cb(news)
    end)
end)

RegisterNUICallback("create-news", function(body, cb)
    lib.callback("b-phone:server:CreateNews", false, function(news)
        cb(news)
    end, body)
end)
