Strings = {
    mining_blips = "miniera",
    intro_instruction = "Premi ~INPUT_ATTACK~ per estrarre il minerale, ~INPUT_FRONTEND_RRIGHT~ per cancellare.",
    mine_rock = "[E] - mina",
    rewarded = "roccia estratta",
    rewarded_desc = "Hai estratto con successo 1x",
    failed_mine = "Fallito",
    failed_mine_desc = "Non sei riuscito a estrarre il minerale!",
    no_pickaxe = "Nessun piccone",
    no_pickaxe_desc = "Non hai un piccone!",
    axe_broke = "piccone rotto",
    axe_broke_desc = "Hai colpito male la roccia, la tua ascia si è spezzata!",
    cantcarry = "Non puoi trasportare",
    cantcarry_desc = "Non hai più spazio per trasportare",
    possible_cheater = "Exploit rilevato",
    possible_cheater_desc = "Sei stato segnalato allo staff.",
    kicked = "Sei stato espulso e segnalato allo staff per possibile imbroglio.",
}
