CreateThread(function()
    AddTextEntry("440i", "BMW 440")
    AddTextEntry("bmwm3e92", "BMW M3e92")
    AddTextEntry("skyline", "SkylineGT-R")
    AddTextEntry("mads14", "Nissan S14 Drift")
    AddTextEntry("tmax", "Tmax500")
    AddTextEntry("slsamg", "Mercedes-BenzSLS")
    AddTextEntry("mgt", "Ford Mustang")
    AddTextEntry("stockade4", "Blindato")
end)
