CreateThread(function()
    AddTextEntry("440i", "BMW 440")
    AddTextEntry("bmwm3e92", "BMW M3e92")
    AddTextEntry("skyline", "SkylineGT-R")
    AddTextEntry("tmax", "Tmax500")
    AddTextEntry("slsamg", "Mercedes-BenzSLS")
    AddTextEntry("mgt", "Ford Mustang")
    AddTextEntry("stockade4", "Blindato")
    AddTextEntry("69charger", "Charger 69")
    AddTextEntry("gxa45", "Mercedes-AMG Classe A")
    AddTextEntry("wide296", "Ferrari 296 GTB")
    AddTextEntry("st3", "Ford Fiesta ST3")
    AddTextEntry("aa_pr911_992_21", "Porsche 911 Turbo S")
    AddTextEntry("25pininfarina", "Pininfarina B95 '25")
    AddTextEntry("blista2", "Fiat Panda Supernova '86 ")
end)
