CreateThread(function()
    AddTextEntry("440i", "BMW 440")
    AddTextEntry("bmwm3e92", "BMW M3e92")
    AddTextEntry("skyline", "SkylineGT-R")
    AddTextEntry("mads14", "Nissan S14 Drift")
    AddTextEntry("tmax", "Tmax500")
    AddTextEntry("slsamg", "Mercedes-BenzSLS")
    AddTextEntry("mgt", "Ford Mustang")
    AddTextEntry("stockade4", "Blindato")
    AddTextEntry("smc690", "KTM690")
    AddTextEntry("69charger", "Charger 69")
    AddTextEntry("gxa45","Mercedes-AMG Classe A")
    AddTextEntry("wide296","Ferrari 296 GTB")
    AddTextEntry("rsq8m", "Audi RSQ8M")
    AddTextEntry("st3", "Ford Fiesta ST3")
    AddTextEntry("aa_pr911_992_21", "Porsche 911 Turbo S")
end)
