// DO NOT EDIT THIS FILE
// Copy it to `config.js` and edit it
window.CONFIG = {
	defaultTemplateId: 'default',
	defaultAltTemplateId: 'defaultAlt',
	templates: {
		'default': '<b>{0}</b>: {1}',
		'defaultAlt': '{0}',
		'print': '<pre>{0}</pre>',
		'example:important': '<h1>^2{0}</h1>',
	},
	fadeTimeout: 3000,
	suggestionLimit: 7,
	style: {
		background: 'rgba(52, 73, 94, 0.00)',
		width: '38%',
		height: '240px',
	},
};
