Config = {
    UseLimitSystem = false, -- Enable if your esx uses limit system
    CraftingStopWithDistance = false, -- Crafting will stop when not near workbench
    ExperiancePerCraft = 5, -- The amount of experiance added per craft (100 Experiance is 1 level)
    HideWhenCantCraft = false, -- Instead of lowering the opacity it hides the item that is not craftable due to low level or wrong job

    Categories = {
        ["tools"] = {
            Label = "Utensili",
            Image = "tools",
            Jobs = { "import" },
        },
        ["accessory"] = {
            Label = "Accessori",
            Image = "accessory",
            Jobs = { "ammu" },
        },
        ["recycled"] = {
            Label = "Riciclo",
            Image = "recycled",
            Jobs = { "import" },
        },
        ["manufacturing"] = {
            Label = "Fabbricazione",
            Image = "manufacturing",
            Jobs = { "import" },
        },
        ["mechanic"] = {
            Label = "Meccanico",
            Image = "Mechanic",
            Jobs = { "mechanic" },
        },
        ["med_equip"] = {
            Label = "Med Equip",
            Image = "bandage",
            Jobs = { "ambulance" },
        },
        ["drugs"] = {
            Label = "Droghe",
            Image = "drugs",
            Jobs = { "ambulance" },
        },
        ["ammu"] = {
            Label = "Armi",
            Image = "ammu",
            Jobs = { "ammu" },
        },
        ["grilled"] = {
            Label = "grigliati",
            Image = "grilled",
            Jobs = { "unicorn" },
        },
        ["fried"] = {
            Label = "Fritti",
            Image = "fried",
            Jobs = { "unicorn" },
        },
        ["sandwiches"] = {
            Label = "Panini",
            Image = "sandwiches",
            Jobs = { "unicorn" },
        },
        ["drinks"] = {
            Label = "drinks",
            Image = "drinks",
            Jobs = { "unicorn" },
        },
        ["sigarette"] = {
            Label = "Sigarette",
            Image = "cigar",
            Jobs = { "ballas", "tridente" },
        },
        ["ammunation"] = {
            Label = "Munizioni",
            Image = "ammu",
            Jobs = { "ammu" },
        },
        ["dessert"] = {
            Label = "Dessert",
            Image = "dessert",
            Jobs = { "unicorn" },
        },
        ["explosives"] = {
            Label = "Esplosivi",
            Image = "explosives",
            Jobs = { "ammu" },
        },
        ["unicorn"] = {
            Label = "Unicorn",
            Image = "unicorn",
            Jobs = { "unicorn" },
        },
    },

    PermanentItems = { -- Items that dont get removed when crafting
        ["wrench"] = true,
    },

    Recipes = { -- Enter Item name and then the speed value! The higher the value the more torque
        ["bandage"] = {
            Level = 0,
            Category = "med_equip",
            isGun = false,
            Jobs = { "ambulance" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 20,
            Ingredients = {
                ["cottonforbandages"] = 2,
            },
        },

        ["medikit"] = {
            Level = 0,
            Category = "med_equip",
            isGun = false,
            Jobs = { "ambulance" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["recycled_plastic"] = 2,
                ["weed"] = 1,
                ["bandage"] = 1,
                ["cottonforbandages"] = 2,
            },
        },

        ["cottonforbandages"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 20,
            Ingredients = {
                ["cotton"] = 4,
            },
        },

        ["ironsheet"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["iron"] = 1,
                ["hammer"] = 1,
            },
        },

        ["steelsheet"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["steel"] = 1,
                ["hammer"] = 1,
            },
        },

        ["diamond_tip"] = {
            Level = 0,
            Category = "tools",
            isGun = false,
            Jobs = { "import", "ballas", "tridente" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["diamond"] = 1,
                ["hammer"] = 1,
                ["steel"] = 1,
            },
        },

        ["recycled_paper"] = {
            Level = 0,
            Category = "recycled",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["paper"] = 2,
            },
        },

        ["diamond_hammer"] = {
            Level = 0,
            Category = "tools",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["diamond"] = 1,
                ["iron"] = 1,
                ["steel"] = 1,
                ["wood"] = 1,
            },
        },

        ["paper"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["newspaper"] = 1,
                ["trash_burgershot"] = 1,
            },
        },

        ["hammer"] = {
            Level = 0,
            Category = "tools",
            isGun = false,
            Jobs = { "import", "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["steel"] = 1,
                ["iron"] = 1,
                ["wood"] = 1,
            },
        },

        ["fixkit"] = {
            Level = 0,
            Category = "mechanic",
            isGun = false,
            Jobs = { "mechanic" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 40,
            Ingredients = {
                ["diamond"] = 1,
                ["ironsheet"] = 1,
                ["hammer"] = 1,
            },
        },

        ["almondmilk"] = {
            Level = 0,
            Category = "drinks",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["ice"] = 2,
                ["almonds"] = 5,
                ["water"] = 1,
            },
        },

        ["appledrink"] = {
            Level = 0,
            Category = "drinks",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 20,
            Ingredients = {
                ["ice"] = 1,
                ["apple"] = 1,
                ["kitchen_knife"] = 1,
            },
        },

        ["cupcake"] = {
            Level = 0,
            Category = "dessert",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 20,
            Ingredients = {
                ["water"] = 1,
                ["flour"] = 1,
            },
        },

        ["fries"] = {
            Level = 0,
            Category = "fried",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 10,
            Ingredients = {
                ["potato"] = 1,
                ["fry_oil"] = 1,
                ["kitchen_knife"] = 1,
            },
        },

        ["mixed_fried_fish"] = {
            Level = 0,
            Category = "fried",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["fry_oil"] = 1,
                ["kitchen_knife"] = 1,
                ["trout"] = 1,
                ["salmon"] = 1,
                ["anchovy"] = 1,
            },
        },

        ["iron"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 10,
            Ingredients = {
                ["hammer"] = 1,
                ["trash_can"] = 10,
            },
        },

        ["cigarette_paper"] = {
            Level = 0,
            Category = "sigarette",
            isGun = false,
            Jobs = { "ballas", "tridente" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 10,
            Ingredients = {
                ["recycled_paper"] = 1,
            },
        },

        ["WEAPON_APPISTOL"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_PISTOL"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_COMBATSHOTGUN"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 5,
                ["wood"] = 1,
                ["steel"] = 10,
                ["hammer"] = 1,
            },
        },

        ["ammo-sniper"] = {
            Level = 10,
            Category = "ammunation",
            isGun = false,
            Jobs = { "ammu", "tridente" },
            JobGrades = { "4", "4" },
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 1,
                ["gunpowder"] = 1,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["ammo-9"] = {
            Level = 10,
            Category = "ammunation",
            isGun = false,
            Jobs = { "ammu", "tridente" },
            JobGrades = { "4", "4" },
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 1,
                ["gunpowder"] = 1,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["ammo-shotgun"] = {
            Level = 10,
            Category = "ammunation",
            isGun = false,
            Jobs = { "ammu", "tridente" },
            JobGrades = { "4", "4" },
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 1,
                ["gunpowder"] = 1,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["ammo-rifle"] = {
            Level = 10,
            Category = "ammunation",
            isGun = false,
            Jobs = { "ammu", "tridente" },
            JobGrades = { "4", "4" },
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 1,
                ["gunpowder"] = 1,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_KNIFE"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["iron"] = 1,
                ["steel"] = 1,
                ["wood"] = 1,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_KNUCKLE"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["iron"] = 2,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_FLASHLIGHT"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["diamond"] = 1,
                ["copper"] = 1,
                ["hammer"] = 1,
                ["recycled_plastic"] = 1,
            },
        },

        ["at_flashlight"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["diamond"] = 1,
                ["copper"] = 1,
                ["hammer"] = 1,
                ["recycled_plastic"] = 1,
            },
        },

        ["at_suppressor_light"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["iron"] = 1,
                ["hammer"] = 1,
                ["steel"] = 2,
            },
        },

        ["WEAPON_NIGHTSTICK"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["recycled_plastic"] = 5,
                ["wood"] = 1,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_SNIPERRIFLE"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["armour"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["steelsheet"] = 1,
                ["ironsheet"] = 1,
                ["hammer"] = 1,
            },
        },

        ["at_skin_luxe"] = {
            Level = 0,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["bread"] = {
            Level = 0,
            Category = "sandwiches",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 120,
            Ingredients = {
                ["flour"] = 4,
                ["water"] = 1,
            },
        },

        ["flour"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 50,
            Ingredients = {
                ["grain"] = 10,
                ["stone_mortar"] = 1,
                ["recycled_plastic"] = 1,
            },
        },

        ["bread_deer"] = {
            Level = 0,
            Category = "unicorn",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 120,
            Ingredients = {
                ["deer_meat"] = 1,
                ["bread"] = 3,
            },
        },

        ["grilled_salmon"] = {
            Level = 0,
            Category = "grilled",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 45,
            Ingredients = {
                ["salmon"] = 1,
                ["kitchen_knife"] = 1,
            },
        },

        ["tuna_sandwich"] = {
            Level = 0,
            Category = "sandwiches",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["tuna"] = 1,
                ["kitchen_knife"] = 1,
                ["bread"] = 1,
            },
        },

        ["grilled_trout"] = {
            Level = 0,
            Category = "grilled",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 45,
            Ingredients = {
                ["trout"] = 1,
                ["kitchen_knife"] = 1,
            },
        },

        ["recycled_plastic"] = {
            Level = 0,
            Category = "recycled",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["plastic_bag"] = 1,
            },
        },

        ["stone_mortar"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["stone"] = 4,
                ["diamond_hammer"] = 1,
            },
        },

        ["contract"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["recycled_paper"] = 2,
            },
        },

        ["weed"] = {
            Level = 0,
            Category = "drugs",
            isGun = false,
            Jobs = { "tridente", "ballas" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["weed_pooch"] = 2,
                ["diamond_tip"] = 1,
                ["recycled_plastic"] = 1,
            },
        },

        ["WEAPON_PISTOL_MK2"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_STUNGUN"] = {
            Level = 0,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_TECPISTOL"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_CARBINERIFLE"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_STICKYBOMB"] = {
            Level = 10,
            Category = "explosives",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["steel"] = 5,
                ["gunpowder"] = 1,
                ["hammer"] = 1,
                ["microchip"] = 1,
            },
        },

        ["microchip"] = {
            Level = 0,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30, -- seconds
            Ingredients = {
                ["copper"] = 4,
                ["iron"] = 2,
                ["steel"] = 1,
                ["steelsheet"] = 1,
                ["diamond_tip"] = 1,
                ["recycled_plastic"] = 2,
            },
        },

        ["kitchen_knife"] = {
            Level = 0,
            Category = "tools",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["recycled_plastic"] = 1,
                ["iron"] = 1,
                ["steel"] = 1,
                ["hammer"] = 1,
            },
        },

        ["axe"] = {
            Level = 0,
            Category = "tools",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["recycled_plastic"] = 1,
                ["iron"] = 1,
                ["steel"] = 1,
                ["hammer"] = 1,
            },
        },
    },

    Workbenches = { -- Every workbench location, leave {} for jobs if you want everybody to access
        {
            coords = vector3(892.338440, -1043.591187, 35.244629),
            jobs = { "import" },
            blip = false,
            recipes = {
                "cottonforbandages",
                "hammer",
                "ironsheet",
                "steelsheet",
                "recycled_paper",
                "paper",
                "recycled_plastic",
                "iron",
                "diamond_tip",
                "diamond_hammer",
                "stone_mortar",
                "contract",
                "flour",
                "kitchen_knife",
                "axe",
            },
            radius = 1.0,
        },
        {
            coords = vector3(311.406586, -564.962646, 43.28210),
            jobs = { "ambulance" },
            blip = false,
            recipes = { "bandage", "medikit" },
            radius = 1.0,
        },
        {
            coords = vector3(-344.492310, -89.063736, 39.002197),
            jobs = { "mechanic" },
            blip = false,
            recipes = { "fixkit" },
            radius = 1.0,
        },
        {
            coords = vector3(808.984619, -2159.630859, 29.616821),
            jobs = { "ammu" },
            blip = false,
            recipes = {
                "WEAPON_APPISTOL",
                "ammo-sniper",
                "ammo-9",
                "ammo-shotgun",
                "WEAPON_KNIFE",
                "WEAPON_KNUCKLE",
                "WEAPON_NIGHTSTICK",
                "WEAPON_PISTOL",
                "armour",
                "WEAPON_FLASHLIGHT",
                "at_suppressor_light",
                "WEAPON_COMBATSHOTGUN",
                "WEAPON_PISTOL_MK2",
                "at_skin_luxe",
                "at_flashlight",
                "hammer",
                "WEAPON_SNIPERRIFLE",
                "WEAPON_STUNGUN",
                "WEAPON_TECPISTOL",
                "WEAPON_CARBINERIFLE",
                "ammo-rifle",
                "microchip",
                "WEAPON_STICKYBOMB",
            },
            radius = 1.0,
        },
        {
            coords = vector3(129.217590, -1283.802246, 29.263062),
            jobs = { "unicorn" },
            blip = false,
            recipes = { "almondmilk", "fries", "grilled_salmon", "grilled_trout", "tuna_sandwich", "appledrink", "bread", "mixed_fried_fish", "cupcake" },
            radius = 1.0,
        },
        {
            coords = vector3(83.156044, -1960.259277, 18.041016),
            jobs = { "ballas" },
            blip = false,
            recipes = { "cigarette_paper", "diamond_tip", "weed" },
            radius = 1.0,
        },
        {
            coords = vector3(-1870.523071, 2061.705566, 135.433716),
            jobs = { "tridente" },
            blip = false,
            recipes = { "hammer", "diamond_tip", "cigarette_paper", "ammo-sniper", "ammo-9", "ammo-shotgun", "weed" },
            radius = 1.0,
        },
    },
}

Config.Locale = "it"
Config.MaxCraftQueue = -1
