Config = {
    UseLimitSystem = false, -- Enable if your esx uses limit system
    CraftingStopWithDistance = false, -- Crafting will stop when not near workbench
    ExperiancePerCraft = 5, -- The amount of experiance added per craft (100 Experiance is 1 level)
    HideWhenCantCraft = false, -- Instead of lowering the opacity it hides the item that is not craftable due to low level or wrong job

    Categories = {
        ["tools"] = {
            Label = "Utensili",
            Image = "tools",
            Jobs = { "import" },
        },
        ["accessory"] = {
            Label = "Accessori",
            Image = "accessory",
            Jobs = { "ammu" },
        },
        ["recycled"] = {
            Label = "Riciclo",
            Image = "recycled",
            Jobs = { "import" },
        },
        ["manufacturing"] = {
            Label = "Fabbricazione",
            Image = "manufacturing",
            Jobs = { "import" },
        },
        ["mechanic"] = {
            Label = "Meccanico",
            Image = "Mechanic",
            Jobs = { "mechanic" },
        },
        ["med_equip"] = {
            Label = "Med Equip",
            Image = "bandage",
            Jobs = { "ambulance" },
        },
        ["drugs"] = {
            Label = "Droghe",
            Image = "drugs",
            Jobs = { "ambulance" },
        },
        ["ammu"] = {
            Label = "Armi",
            Image = "ammu",
            Jobs = { "ammu" },
        },
        ["unicorn"] = {
            Label = "Unicorn",
            Image = "unicorn",
            Jobs = { "unicorn" },
        },
        ["ballas"] = {
            Label = "Ballas",
            Image = "ballas",
            Jobs = { "ballas" },
        },
        ["baker"] = {
            Label = "Baker",
            Image = "baker",
            Jobs = { "baker" },
        },
        ["fisherman"] = {
            Label = "fisherman",
            Image = "fisherman",
            Jobs = { "unicorn" },
        },
        ["ammunation"] = {
            Label = "Munizioni",
            Image = "ammu",
            Jobs = { "ammu" },
        },
    },

    PermanentItems = { -- Items that dont get removed when crafting
        ["wrench"] = true,
    },

    Recipes = { -- Enter Item name and then the speed value! The higher the value the more torque
        ["bandage"] = {
            Level = 0,
            Category = "med_equip",
            isGun = false,
            Jobs = { "ambulance" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 20,
            Ingredients = {
                ["cottonforbandages"] = 2,
            },
        },

        ["medikit"] = {
            Level = 0,
            Category = "med_equip",
            isGun = false,
            Jobs = { "ambulance" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["recycled_plastic"] = 2,
                ["marijuana"] = 5,
                ["bandage"] = 1,
                ["cottonforbandages"] = 2,
                ["marijuana_extract"] = 2,
            },
        },

        ["marijuana_extract"] = {
            Level = 0,
            Category = "drugs",
            isGun = false,
            Jobs = { "ambulance" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["marijuana"] = 2,
                ["diamond_tip"] = 1,
                ["bandage"] = 1,
            },
        },

        ["marijuana"] = {
            Level = 0,
            Category = "drugs",
            isGun = false,
            Jobs = { "ambulance" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 20,
            Ingredients = {
                ["cannabis"] = 2,
                ["diamond_tip"] = 1,
            },
        },

        ["cottonforbandages"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 20,
            Ingredients = {
                ["cotton"] = 4,
            },
        },

        ["ironsheet"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 5,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["iron"] = 1,
                ["hammer"] = 1,
            },
        },

        ["steelsheet"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 5,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["steel"] = 1,
                ["hammer"] = 1,
            },
        },

        ["diamond_tip"] = {
            Level = 0,
            Category = "tools",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["diamond"] = 1,
                ["hammer"] = 1,
                ["steel"] = 1,
            },
        },

        ["recycled_paper"] = {
            Level = 0,
            Category = "recycled",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["paper"] = 2,
            },
        },

        ["paper"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 6,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["newspaper"] = 1,
                ["trash_burgershot"] = 1,
            },
        },

        ["hammer"] = {
            Level = 0,
            Category = "tools",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 4,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["iron"] = 2,
                ["wood"] = 1,
            },
        },

        ["fixkit"] = {
            Level = 0,
            Category = "mechanic",
            isGun = false,
            Jobs = { "mechanic" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["ironsheet"] = 2,
                ["hammer"] = 1,
            },
        },

        ["almondmilk"] = {
            Level = 0,
            Category = "unicorn",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["ice"] = 2,
                ["almonds"] = 5,
                ["water"] = 1,
            },
        },

        ["fries"] = {
            Level = 0,
            Category = "unicorn",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 5,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 10,
            Ingredients = {
                ["potato"] = 1,
                ["fry_oil"] = 1,
                ["WEAPON_KNIFE"] = 1,
            },
        },

        ["iron"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 3,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 10,
            Ingredients = {
                ["hammer"] = 1,
                ["trash_can"] = 10,
            },
        },

        ["cigarette_paper"] = {
            Level = 0,
            Category = "ballas",
            isGun = false,
            Jobs = { "ballas" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 10,
            Ingredients = {
                ["recycled_paper"] = 1,
            },
        },

        ["WEAPON_APPISTOL"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_PISTOL"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_COMBATSHOTGUN"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 5,
                ["wood"] = 1,
                ["steel"] = 10,
                ["hammer"] = 1,
            },
        },

        ["ammo-sniper"] = {
            Level = 10,
            Category = "ammunation",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 1,
                ["gunpowder"] = 1,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["ammo-9"] = {
            Level = 10,
            Category = "ammunation",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 10,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 1,
                ["gunpowder"] = 1,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["ammo-shotgun"] = {
            Level = 10,
            Category = "ammunation",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 10,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 1,
                ["gunpowder"] = 1,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_KNIFE"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["iron"] = 1,
                ["steel"] = 1,
                ["wood"] = 1,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_KNUCKLE"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["iron"] = 2,
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["WEAPON_FLASHLIGHT"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["diamond"] = 1,
                ["copper"] = 1,
                ["hammer"] = 1,
                ["recycled_plastic"] = 1,
            },
        },

        ["at_suppressor_light"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["iron"] = 1,
                ["hammer"] = 1,
                ["steel"] = 2,
            },
        },

        ["WEAPON_NIGHTSTICK"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["recycled_plastic"] = 5,
                ["wood"] = 1,
                ["hammer"] = 1,
            },
        },

        ["armour"] = {
            Level = 10,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["steelsheet"] = 1,
                ["ironsheet"] = 1,
                ["hammer"] = 1,
            },
        },

        ["at_skin_luxe"] = {
            Level = 0,
            Category = "accessory",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["gold"] = 1,
                ["hammer"] = 1,
            },
        },

        ["bread"] = {
            Level = 0,
            Category = "baker",
            isGun = false,
            Jobs = { "baker" },
            JobGrades = {},
            Amount = 5,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 200,
            Ingredients = {
                ["flour"] = 1,
            },
        },

        ["flour"] = {
            Level = 0,
            Category = "baker",
            isGun = false,
            Jobs = { "baker" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 120,
            Ingredients = {
                ["grain"] = 10,
            },
        },

        ["bread_deer"] = {
            Level = 0,
            Category = "unicorn",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 3,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 120,
            Ingredients = {
                ["deer_meat"] = 1,
                ["bread"] = 3,
            },
        },

        ["salmon_fillet"] = {
            Level = 0,
            Category = "fisherman",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 2,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["salmon"] = 1,
                ["WEAPON_KNIFE"] = 1,
            },
        },

        ["grilled_salmon"] = {
            Level = 0,
            Category = "fisherman",
            isGun = false,
            Jobs = { "unicorn" },
            JobGrades = {},
            Amount = 2,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 60,
            Ingredients = {
                ["salmon_fillet"] = 1,
            },
        },

        ["recycled_plastic"] = {
            Level = 0,
            Category = "recycled",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 2,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["plastic_bag"] = 1,
            },
        },

        ["contract"] = {
            Level = 0,
            Category = "manufacturing",
            isGun = false,
            Jobs = { "import" },
            JobGrades = {},
            Amount = 2,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 30,
            Ingredients = {
                ["recycled_paper"] = 2,
            },
        },

        ["WEAPON_PISTOL_MK2"] = {
            Level = 10,
            Category = "ammu",
            isGun = false,
            Jobs = { "ammu" },
            JobGrades = {},
            Amount = 1,
            SuccessRate = 100,
            requireBlueprint = false,
            Time = 180,
            Ingredients = {
                ["copper"] = 1,
                ["iron"] = 3,
                ["wood"] = 1,
                ["steel"] = 5,
                ["hammer"] = 1,
            },
        },
    },

    Workbenches = { -- Every workbench location, leave {} for jobs if you want everybody to access
        {
            coords = vector3(1020.936279, -2404.628662, 30.122314),
            jobs = { "import" },
            blip = false,
            recipes = {
                "cottonforbandages",
                "hammer",
                "ironsheet",
                "steelsheet",
                "recycled_paper",
                "paper",
                "recycled_plastic",
                "iron",
                "diamond_tip",
                "contract",
            },
            radius = 1.0,
        },
        {
            coords = vector3(365.432983, -1384.470337, 32.413940),
            jobs = { "ambulance" },
            blip = false,
            recipes = { "bandage", "marijuana", "marijuana_extract", "medikit" },
            radius = 1.0,
        },
        {
            coords = vector3(-344.492310, -89.063736, 39.002197),
            jobs = { "mechanic" },
            blip = false,
            recipes = { "fixkit" },
            radius = 1.0,
        },
        {
            coords = vector3(808.984619, -2159.630859, 29.616821),
            jobs = { "ammu" },
            blip = false,
            recipes = {
                "WEAPON_APPISTOL",
                "ammo-sniper",
                "ammo-9",
                "ammo-shotgun",
                "WEAPON_KNIFE",
                "WEAPON_KNUCKLE",
                "WEAPON_NIGHTSTICK",
                "WEAPON_PISTOL",
                "armour",
                "WEAPON_FLASHLIGHT",
                "at_suppressor_light",
                "WEAPON_COMBATSHOTGUN",
                "WEAPON_PISTOL_MK2",
                "at_skin_luxe",
            },
            radius = 1.0,
        },
        {
            coords = vector3(129.217590, -1283.802246, 29.263062),
            jobs = { "unicorn" },
            blip = false,
            recipes = { "almondmilk", "fries", "salmon_fillet", "grilled_salmon" },
            radius = 1.0,
        },
        {
            coords = vector3(83.156044, -1960.259277, 18.041016),
            jobs = { "ballas" },
            blip = false,
            recipes = { "cigarette_paper", "marijuana" },
            radius = 1.0,
        },
        {
            coords = vector3(2342.202148, 3144.817627, 48.202148),
            jobs = { "baker" },
            blip = false,
            recipes = { "flour", "bread" },
            radius = 1.0,
        },
    },
}

Config.Locale = "it"
